# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21def2bcfdf5283c1ae5b248e58237d09eca0ddf7674d80196067e9191feaf6718147ebf2fce0e53111d58e8c8281f615b4d329fa43c6170ee83fcfaf31db6a

test:
  secret_key_base: e75f05bb4a70648366c32eccd1b28eb1a8c28a01d7269463116be7f115a946d831693ef73dd2a6da047574159be0dc79513828752307bc4db5b62444b9d08028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
